# Generated by Django 3.1 on 2021-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210220_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
