# Generated by Django 3.0.6 on 2020-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('PRT', 'Portofolio'), ('IDE', 'Idea')], max_length=4),
        ),
    ]
