# Generated by Django 3.0.6 on 2020-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200531_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.CharField(default='https://suraudata.xyz', max_length=200),
        ),
    ]
