# Generated by Django 3.0.6 on 2020-10-03 12:32

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_posts_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
