# Generated by Django 3.0.6 on 2020-10-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20201003_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at']},
        ),
    ]
